//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.21 at 02:40:54 PM BRST 
//


package br.gov.dados.script.config.mapping.ckanconfig.impl;

import br.gov.dados.script.config.mapping.ckanconfig.CkanConfigParamsType;
import br.gov.dados.script.config.mapping.ckanconfig.CkanConfig;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.gov.dados.script.config.mapping.ckanconfig package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.gov.dados.script.config.mapping.ckanconfig
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CkanConfigParamsType }
     * 
     */
    public CkanConfigParamsType createCkanConfigParamsType() {
        return new CkanConfigParamsType();
    }

    /**
     * Create an instance of {@link CkanConfig }
     * 
     */
    public CkanConfig createCkanConfig() {
        return new CkanConfig();
    }

    /**
     * Create an instance of {@link CkanConfigParamsType.CkanConnection }
     * 
     */
    public CkanConfigParamsType.CkanConnection createCkanConfigParamsTypeCkanConnection() {
        return new CkanConfigParamsType.CkanConnection();
    }

    /**
     * Create an instance of {@link CkanConfigParamsType.CkanDataset }
     * 
     */
    public CkanConfigParamsType.CkanDataset createCkanConfigParamsTypeCkanDataset() {
        return new CkanConfigParamsType.CkanDataset();
    }

}
