//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.21 at 02:40:54 PM BRST 
//


package br.gov.dados.script.config.mapping.ckanconfig;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ckan-config-params" type="{http://www.dados.gov.br/ns/script/ckan-config}ckan-config-params-type" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ckanConfigParams"
})
@XmlRootElement(name = "ckan-config")
public class CkanConfig
    implements Serializable
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "ckan-config-params", required = true)
    protected List<CkanConfigParamsType> ckanConfigParams;

    /**
     * Gets the value of the ckanConfigParams property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ckanConfigParams property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCkanConfigParams().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CkanConfigParamsType }
     * 
     * 
     */
    public List<CkanConfigParamsType> getCkanConfigParams() {
        if (ckanConfigParams == null) {
            ckanConfigParams = new ArrayList<CkanConfigParamsType>();
        }
        return this.ckanConfigParams;
    }

    /**
     * Sets the value of the ckanConfigParams property.
     * 
     * @param ckanConfigParams
     *     allowed object is
     *     {@link CkanConfigParamsType }
     *     
     */
    public void setCkanConfigParams(List<CkanConfigParamsType> ckanConfigParams) {
        this.ckanConfigParams = ckanConfigParams;
    }

}
