//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.21 at 02:40:54 PM BRST 
//


package br.gov.dados.script.config.mapping.ckanconfig;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ckan-config-params-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ckan-config-params-type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ckan-connection">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="url-api" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="api-key" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ckan-dataset" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="author-email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="maintainer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="maintainer-email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="license-id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="notes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="tags" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="resources-csv-path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="groups-csv-path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ckan-config-params-type", propOrder = {
    "ckanConnection",
    "ckanDataset"
})
public class CkanConfigParamsType
    implements Serializable
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "ckan-connection", required = true)
    protected CkanConfigParamsType.CkanConnection ckanConnection;
    @XmlElement(name = "ckan-dataset", required = true)
    protected List<CkanConfigParamsType.CkanDataset> ckanDataset;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the ckanConnection property.
     * 
     * @return
     *     possible object is
     *     {@link CkanConfigParamsType.CkanConnection }
     *     
     */
    public CkanConfigParamsType.CkanConnection getCkanConnection() {
        return ckanConnection;
    }

    /**
     * Sets the value of the ckanConnection property.
     * 
     * @param value
     *     allowed object is
     *     {@link CkanConfigParamsType.CkanConnection }
     *     
     */
    public void setCkanConnection(CkanConfigParamsType.CkanConnection value) {
        this.ckanConnection = value;
    }

    /**
     * Gets the value of the ckanDataset property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ckanDataset property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCkanDataset().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CkanConfigParamsType.CkanDataset }
     * 
     * 
     */
    public List<CkanConfigParamsType.CkanDataset> getCkanDataset() {
        if (ckanDataset == null) {
            ckanDataset = new ArrayList<CkanConfigParamsType.CkanDataset>();
        }
        return this.ckanDataset;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Sets the value of the ckanDataset property.
     * 
     * @param ckanDataset
     *     allowed object is
     *     {@link CkanConfigParamsType.CkanDataset }
     *     
     */
    public void setCkanDataset(List<CkanConfigParamsType.CkanDataset> ckanDataset) {
        this.ckanDataset = ckanDataset;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="url-api" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="api-key" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class CkanConnection
        implements Serializable
    {

        private final static long serialVersionUID = 100L;
        @XmlElement(name = "url-api", required = true)
        protected String urlApi;
        @XmlElement(name = "api-key", required = true)
        protected String apiKey;

        /**
         * Gets the value of the urlApi property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUrlApi() {
            return urlApi;
        }

        /**
         * Sets the value of the urlApi property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUrlApi(String value) {
            this.urlApi = value;
        }

        /**
         * Gets the value of the apiKey property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApiKey() {
            return apiKey;
        }

        /**
         * Sets the value of the apiKey property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApiKey(String value) {
            this.apiKey = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="author-email" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="maintainer" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="maintainer-email" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="license-id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="notes" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="tags" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="resources-csv-path" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="groups-csv-path" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class CkanDataset
        implements Serializable
    {

        private final static long serialVersionUID = 100L;
        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        protected String title;
        @XmlElement(required = true)
        protected String url;
        @XmlElement(required = true)
        protected String author;
        @XmlElement(name = "author-email", required = true)
        protected String authorEmail;
        @XmlElement(required = true)
        protected String maintainer;
        @XmlElement(name = "maintainer-email", required = true)
        protected String maintainerEmail;
        @XmlElement(name = "license-id", required = true)
        protected String licenseId;
        @XmlElement(required = true)
        protected String version;
        @XmlElement(required = true)
        protected String notes;
        @XmlElement(required = true)
        protected String tags;
        @XmlElement(required = true)
        protected String state;
        @XmlElement(name = "resources-csv-path", required = true)
        protected String resourcesCsvPath;
        @XmlElement(name = "groups-csv-path", required = true)
        protected String groupsCsvPath;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the url property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUrl() {
            return url;
        }

        /**
         * Sets the value of the url property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUrl(String value) {
            this.url = value;
        }

        /**
         * Gets the value of the author property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAuthor() {
            return author;
        }

        /**
         * Sets the value of the author property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAuthor(String value) {
            this.author = value;
        }

        /**
         * Gets the value of the authorEmail property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAuthorEmail() {
            return authorEmail;
        }

        /**
         * Sets the value of the authorEmail property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAuthorEmail(String value) {
            this.authorEmail = value;
        }

        /**
         * Gets the value of the maintainer property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMaintainer() {
            return maintainer;
        }

        /**
         * Sets the value of the maintainer property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMaintainer(String value) {
            this.maintainer = value;
        }

        /**
         * Gets the value of the maintainerEmail property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMaintainerEmail() {
            return maintainerEmail;
        }

        /**
         * Sets the value of the maintainerEmail property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMaintainerEmail(String value) {
            this.maintainerEmail = value;
        }

        /**
         * Gets the value of the licenseId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLicenseId() {
            return licenseId;
        }

        /**
         * Sets the value of the licenseId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLicenseId(String value) {
            this.licenseId = value;
        }

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVersion(String value) {
            this.version = value;
        }

        /**
         * Gets the value of the notes property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNotes() {
            return notes;
        }

        /**
         * Sets the value of the notes property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNotes(String value) {
            this.notes = value;
        }

        /**
         * Gets the value of the tags property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTags() {
            return tags;
        }

        /**
         * Sets the value of the tags property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTags(String value) {
            this.tags = value;
        }

        /**
         * Gets the value of the state property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getState() {
            return state;
        }

        /**
         * Sets the value of the state property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setState(String value) {
            this.state = value;
        }

        /**
         * Gets the value of the resourcesCsvPath property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResourcesCsvPath() {
            return resourcesCsvPath;
        }

        /**
         * Sets the value of the resourcesCsvPath property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResourcesCsvPath(String value) {
            this.resourcesCsvPath = value;
        }

        /**
         * Gets the value of the groupsCsvPath property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGroupsCsvPath() {
            return groupsCsvPath;
        }

        /**
         * Sets the value of the groupsCsvPath property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGroupsCsvPath(String value) {
            this.groupsCsvPath = value;
        }

    }

}
