//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.21 at 02:40:54 PM BRST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.dados.gov.br/ns/script/ckan-config", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,location="br/gov/dados/script/config/xsd/ckan-config.xsd")
package br.gov.dados.script.config.mapping.ckanconfig;
